# Generated by Django 5.1.5 on 2025-01-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
